version: '3.5'

services:
  # LAMP Server
  lamp-c7:
    container_name: lamp-c7
    build: 
      context: ./docker_files
      dockerfile: lamp-c7
    tty: true
    volumes:
      # for Systemd integration:https://hub.docker.com/_/centos
      - /sys/fs/cgroup:/sys/fs/cgroup:ro 
      - ${MAKE_TEMP}:/run
      # shared database
      - mariadb:/var/lib/mysql
      # copy flexiapi env file
      - ./flexiapi_env/flexiapi.env:/opt/belledonne-communications/share/flexisip-account-manager/flexiapi/.env
      # for laravel php framework
      # - ./html:/var/www/html:rw
      # - ./etc/flexisip-account-manager:/etc/flexisip-account-manager:rw
      # shared apache default.conf between host and container
      # - ./etc/http:/etc/http/conf.d/default.conf
      # shared the directory /var/www/html
      # - ./html:/var/www/html 
    restart: always
    network_mode: host
    cap_add:
      - SYS_ADMIN
    privileged: true
    devices:
      - /dev/fuse

# need to "$ docker volume create mariadb"
volumes:
  mariadb:
    external: true 
