version: '3.5'

services:
  # Flexisip SIP Server
  flexisip-c7:
    container_name: flexisip-c7
    build: 
      context: ./docker_files
      dockerfile: flexisip-c7
    tty: true   
    volumes:
      # for Systemd integration:https://hub.docker.com/_/centos
      - /sys/fs/cgroup:/sys/fs/cgroup:ro 
      - ${MAKE_TEMP}:/run
      #- ./letsencrypt:/etc/flexisip/tls
      - ./config:/etc/flexisip
     ### If you are using TLS Support for Apache to listen on 443 in the container drop them in /certs and set these:
      #- TLS_CERT=cert.pem
      #- TLS_KEY=key.pem
    restart: always
    network_mode: host
    cap_add:
      - SYS_ADMIN
    privileged: true
    devices:
      - /dev/fuse
